### PR TITLE
Unique ami names

### PR DESCRIPTION
**Pull request by dougbyrne**
Need to add instance id to make AMI names unique.

### CODE REVIEW

**Comment by nathants** [comment]
this would break stuff. there is code that unpacks after `.split('__')`.

more importantly, ami names are not supposed to be unique, there are supposed to be many amis per name, and usually you want the latest one, which is at the top of the list with `ec2 amis $name`.

what is the use case here? @dougbyrne

**Comment by dougbyrne** [comment]
If I try to create an AMI with a duplicate name I get an error. For example, the ES snapshots all end up with the same AMI name: `AMI name elasticsearch-prod__2017-06-09T10_00_42.554924Z is already in use by AMI ami-xxx` We can make it unique some other way, but we have to do something for it.

**Comment by nathants** [comment]
if name is actually $name__$date, doesn't the date provide pretty good deduplication? i suppose we could make date longer, currently it's year-month-day, which means you can't make more than one ami per minute.

**Comment by nathants** [comment]
or perhaps just pass $instance-id as part of the name, if that's really what you want?

**Comment by dougbyrne** [comment]
For the ES snapshots at least, the whole cluster will have snapshots named `elasticsearch-prod::i-xxx::2017-06-09T10_00_42.554924Z`. They all got started at the same time, so they have the same timestamp in that name.

We could do AMI names like `elasticsearch-prod-i-xxx__2017-06-09T10_00_42.554924Z`, that seems like it would keep it from breaking whatever you have going on in `ec2 amis`? I'm not attached to using the instance ID, it was just an easy source of entropy.

**Comment by nathants** [comment]
how about dropping down to the aws cli? http://docs.aws.amazon.com/cli/latest/reference/ec2/create-image.html

**Comment by dougbyrne** [comment]
I'm not sure I'm understanding your objection. Right now, creating AMIs for a cluster using `ec2 snapshots --create-ami` will fail because it will attempt to create all the AMIs with the same name. What else can we do?

**Comment by nathants** [comment]
well that's embarrassing. totally thought this was part of `def ami ...` when it's actually `def snapshots ...`. 

separate this from that other commit, and i'll merge it.

**Pull request merged**
